#!/bin/sh -e

usage() { 
	echo "timesrc version 1.0 - Copyright (C) 2015 Intelight Inc."
	echo ""
	echo "usage:   timesrc - print current time source"
	echo "         timesrc <name> - set current time source [LINESYNC/RTCSQWR/CRYSTAL]"
	echo "         timesrc EXTERNAL1 <port> - set GPS time source for serial port"
	echo "         timesrc EXTERNAL2 <hostname> - set NTP time source"
}

currentSource() { 
	if grep -q LSYN /etc/chrony.conf; then
		echo "Current timesrc is LINESYNC(0)"
	elif grep -q RTC /etc/chrony.conf; then
		echo "Current timesrc is RTCSQWR(1)"
	elif grep -q GPS /etc/chrony.conf; then
		echo "Current timesrc is EXTERNAL1(3)"
	elif grep -q server /etc/chrony.conf; then
		echo "Current timesrc is EXTERNAL2(4)"
	else
		echo "Current timesrc is CRYSTAL(2)"
	fi
}

setSource() {
	currentSource

	sed -i '/LSYN/d;/RTC/d;/GPS/d;/server/d' /etc/chrony.conf
	sed -i '/export DEVICES=/c\export DEVICES=""' /etc/gpsd.conf	

	case "$1" in
		LINESYNC)
			echo "setting timesrc to LINESYNC(0)"
			sed -i '1s|^|refclock PPS /dev/pps0 poll 2 filter 16 refid LSYN\n|' /etc/chrony.conf
			;;
		RTCSQWR)
			echo "setting timesrc to RTCSQWR(1)"
			sed -i '1s|^|refclock PPS /dev/pps1 poll 2 filter 16 refid RTC\n|' /etc/chrony.conf
			;;
		CRYSTAL)
			echo "setting timesrc to CRYSTAL(2)"
			;;
		EXTERNAL1)
			echo "setting timesrc to EXTERNAL1(3)"
			port=$(cat /etc/mdev.conf | grep -w sp$2 | awk '{print $1}')
			sed -i "1s|^|refclock SOCK /var/run/chrony.$port.sock refid GPSD\n|" /etc/chrony.conf
			sed -i "/export DEVICES=/c\export DEVICES=\"/dev/$port\"" /etc/gpsd.conf	
			;;
		EXTERNAL2)
			echo "setting timesrc to EXTERNAL2(4)"
			sed -i "1s|^|server $2 iburst\n|" /etc/chrony.conf
			;;
	esac

	/etc/init.d/S50gpsd stop
	/etc/init.d/S49chrony stop
	adjtimex -t 10000 -f 0 || true
	rm -rf /var/lib/chrony/dumpdir
	/etc/init.d/S49chrony start
	/etc/init.d/S50gpsd start
}

if [ "$#" = "0" ]; then
	currentSource
	exit 0
fi

case "$1" in
	LINESYNC|RTCSQWR|CRYSTAL)
		setSource $1
		;;
	EXTERNAL1|EXTERNAL2)
		if [ -z "$2" ]; then
			echo "missing argument $@"
			usage
			exit 1
		fi
		setSource $1 $2
		;;
	--help)
		usage
		;;
	*)
		echo "Unrecognized timesrc $@"
		usage
		exit 1
		;;
esac

